name: Heritage Reminder - v1
on:
  schedule:
    - cron: '0 15 * * 4'

permissions:
  contents: read

jobs:
  build:
    environment: scheduled_report
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: it_IT.UTF-8
      env:
        LANG: "it_IT.UTF-8"
      run: |
          sudo locale-gen ${{ env.LANG }}
          sudo update-locale ${{ env.LANG }}
    - name: Run GitHub feed -
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      run: |
        python src/reminder.py
