# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: IO report
on:
  push:
    branches: ["add-github-scheduled-action"]
#on:
#  schedule:
#    - cron: '55 13 * * 5'

permissions:
  contents: read

jobs:
  build:
    environment: scheduled_report
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: it_IT.UTF-8
      env:
        LANG: "it_IT.UTF-8"
      run: |
          sudo locale-gen ${{ env.LANG }}
          sudo update-locale ${{ env.LANG }}
    - name: Run GitHub feed
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        slack_token: '${{ secrets.slack_token }}'
      run: |
        python src/main.py
